### ISSUE TITLE
Update metal-uri to v3.0.0

### ISSUE THREAD

**Issue by ipeychev** [metal/metal-ajax#15]
Metal Uri 3.0.0 is compatible and runs in other environments apart from Node and browses - ReactNative, ReactVR, etc.
Metal Ajax depends on Metal Uri, so this module has to be updated here to allow Metal Ajax to work in these environments too.

**Comment by jbalsas** [comment]
This has been merged to the `develop` branch and scheduled for `3.0.0` milestone!
